// Code generated by MockGen. DO NOT EDIT.
// Source: configmap.go
//
// Generated by this command:
//
//	mockgen -source=configmap.go -package=configmap -destination=mock_configmap.go ConfigMapAPI
//
// Package configmap is a generated GoMock package.
package configmap

import (
	reflect "reflect"

	v1beta1 "github.com/awslabs/operator-for-ai-chips-on-aws/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockConfigMapAPI is a mock of ConfigMapAPI interface.
type MockConfigMapAPI struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMapAPIMockRecorder
}

// MockConfigMapAPIMockRecorder is the mock recorder for MockConfigMapAPI.
type MockConfigMapAPIMockRecorder struct {
	mock *MockConfigMapAPI
}

// NewMockConfigMapAPI creates a new mock instance.
func NewMockConfigMapAPI(ctrl *gomock.Controller) *MockConfigMapAPI {
	mock := &MockConfigMapAPI{ctrl: ctrl}
	mock.recorder = &MockConfigMapAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigMapAPI) EXPECT() *MockConfigMapAPIMockRecorder {
	return m.recorder
}

// SetBuildConfigMapAsDesired mocks base method.
func (m *MockConfigMapAPI) SetBuildConfigMapAsDesired(buildCM *v1.ConfigMap, devConfig *v1beta1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBuildConfigMapAsDesired", buildCM, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildConfigMapAsDesired indicates an expected call of SetBuildConfigMapAsDesired.
func (mr *MockConfigMapAPIMockRecorder) SetBuildConfigMapAsDesired(buildCM, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBuildConfigMapAsDesired", reflect.TypeOf((*MockConfigMapAPI)(nil).SetBuildConfigMapAsDesired), buildCM, devConfig)
}
