// Code generated by MockGen. DO NOT EDIT.
// Source: kmmmodule.go
//
// Generated by this command:
//
//	mockgen -source=kmmmodule.go -package=kmmmodule -destination=mock_kmmmodule.go KMMModuleAPI
//
// Package kmmmodule is a generated GoMock package.
package kmmmodule

import (
	reflect "reflect"

	v1beta1 "github.com/awslabs/operator-for-ai-chips-on-aws/api/v1beta1"
	v1beta10 "github.com/rh-ecosystem-edge/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
)

// MockKMMModuleAPI is a mock of KMMModuleAPI interface.
type MockKMMModuleAPI struct {
	ctrl     *gomock.Controller
	recorder *MockKMMModuleAPIMockRecorder
}

// MockKMMModuleAPIMockRecorder is the mock recorder for MockKMMModuleAPI.
type MockKMMModuleAPIMockRecorder struct {
	mock *MockKMMModuleAPI
}

// NewMockKMMModuleAPI creates a new mock instance.
func NewMockKMMModuleAPI(ctrl *gomock.Controller) *MockKMMModuleAPI {
	mock := &MockKMMModuleAPI{ctrl: ctrl}
	mock.recorder = &MockKMMModuleAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMMModuleAPI) EXPECT() *MockKMMModuleAPIMockRecorder {
	return m.recorder
}

// SetKMMModuleAsDesired mocks base method.
func (m *MockKMMModuleAPI) SetKMMModuleAsDesired(mod *v1beta10.Module, devConfig *v1beta1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKMMModuleAsDesired", mod, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKMMModuleAsDesired indicates an expected call of SetKMMModuleAsDesired.
func (mr *MockKMMModuleAPIMockRecorder) SetKMMModuleAsDesired(mod, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKMMModuleAsDesired", reflect.TypeOf((*MockKMMModuleAPI)(nil).SetKMMModuleAsDesired), mod, devConfig)
}
