// Code generated by MockGen. DO NOT EDIT.
// Source: dradriver.go
//
// Generated by this command:
//
//	mockgen -source=dradriver.go -package=dradriver -destination=mock_dradriver.go DRADriver
//
// Package dradriver is a generated GoMock package.
package dradriver

import (
	reflect "reflect"

	v1beta1 "github.com/awslabs/operator-for-ai-chips-on-aws/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
)

// MockDRADriver is a mock of DRADriver interface.
type MockDRADriver struct {
	ctrl     *gomock.Controller
	recorder *MockDRADriverMockRecorder
}

// MockDRADriverMockRecorder is the mock recorder for MockDRADriver.
type MockDRADriverMockRecorder struct {
	mock *MockDRADriver
}

// NewMockDRADriver creates a new mock instance.
func NewMockDRADriver(ctrl *gomock.Controller) *MockDRADriver {
	mock := &MockDRADriver{ctrl: ctrl}
	mock.recorder = &MockDRADriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDRADriver) EXPECT() *MockDRADriverMockRecorder {
	return m.recorder
}

// SetDRADriverAsDesired mocks base method.
func (m *MockDRADriver) SetDRADriverAsDesired(ds *v1.DaemonSet, devConfig *v1beta1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDRADriverAsDesired", ds, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDRADriverAsDesired indicates an expected call of SetDRADriverAsDesired.
func (mr *MockDRADriverMockRecorder) SetDRADriverAsDesired(ds, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDRADriverAsDesired", reflect.TypeOf((*MockDRADriver)(nil).SetDRADriverAsDesired), ds, devConfig)
}
