// Code generated by MockGen. DO NOT EDIT.
// Source: customscheduler.go
//
// Generated by this command:
//
//	mockgen -source=customscheduler.go -package=customscheduler -destination=mock_customscheduler.go CustomScheduler
//
// Package customscheduler is a generated GoMock package.
package customscheduler

import (
	reflect "reflect"

	v1beta1 "github.com/awslabs/operator-for-ai-chips-on-aws/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
)

// MockCustomScheduler is a mock of CustomScheduler interface.
type MockCustomScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockCustomSchedulerMockRecorder
}

// MockCustomSchedulerMockRecorder is the mock recorder for MockCustomScheduler.
type MockCustomSchedulerMockRecorder struct {
	mock *MockCustomScheduler
}

// NewMockCustomScheduler creates a new mock instance.
func NewMockCustomScheduler(ctrl *gomock.Controller) *MockCustomScheduler {
	mock := &MockCustomScheduler{ctrl: ctrl}
	mock.recorder = &MockCustomSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomScheduler) EXPECT() *MockCustomSchedulerMockRecorder {
	return m.recorder
}

// SetCustomSchedulerAsDesired mocks base method.
func (m *MockCustomScheduler) SetCustomSchedulerAsDesired(dp *v1.Deployment, devConfig *v1beta1.DeviceConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCustomSchedulerAsDesired", dp, devConfig)
}

// SetCustomSchedulerAsDesired indicates an expected call of SetCustomSchedulerAsDesired.
func (mr *MockCustomSchedulerMockRecorder) SetCustomSchedulerAsDesired(dp, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCustomSchedulerAsDesired", reflect.TypeOf((*MockCustomScheduler)(nil).SetCustomSchedulerAsDesired), dp, devConfig)
}

// SetCustomSchedulerExtensionAsDesired mocks base method.
func (m *MockCustomScheduler) SetCustomSchedulerExtensionAsDesired(dp *v1.Deployment, devConfig *v1beta1.DeviceConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCustomSchedulerExtensionAsDesired", dp, devConfig)
}

// SetCustomSchedulerExtensionAsDesired indicates an expected call of SetCustomSchedulerExtensionAsDesired.
func (mr *MockCustomSchedulerMockRecorder) SetCustomSchedulerExtensionAsDesired(dp, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCustomSchedulerExtensionAsDesired", reflect.TypeOf((*MockCustomScheduler)(nil).SetCustomSchedulerExtensionAsDesired), dp, devConfig)
}
