apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-nfd-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - nfd.openshift.io
  resources:
  - nodefeaturediscoveries
  - nodefeaturerules
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - k8s.aws
  resources:
  - deviceconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-nfd-clusterrole-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argocd-nfd-clusterrole
  apiGroup: rbac.authorization.k8s.io
