{{- if .Values.deviceConfig.draDriverVersion }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awslabs-gpu-operator-dra-driver
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awslabs-gpu-operator-dra-driver
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceslices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - deviceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awslabs-gpu-operator-dra-driver
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awslabs-gpu-operator-dra-driver
subjects:
- kind: ServiceAccount
  name: awslabs-gpu-operator-dra-driver
  namespace: {{ .Values.namespace }}
{{- end }}
