{{- if .Values.compileCachePVC.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.compileCachePVC.name }}
  namespace: {{ .Values.servingRuntime.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.compileCachePVC.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.compileCachePVC.size }}
{{- end }}
