// Code generated by MockGen. DO NOT EDIT.
// Source: upgrade.go
//
// Generated by this command:
//
//	mockgen -source=upgrade.go -package=upgrade -destination=mock_upgrade.go UpgradeAPI
//
// Package upgrade is a generated GoMock package.
package upgrade

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/awslabs/operator-for-ai-chips-on-aws/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockUpgradeAPI is a mock of UpgradeAPI interface.
type MockUpgradeAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUpgradeAPIMockRecorder
}

// MockUpgradeAPIMockRecorder is the mock recorder for MockUpgradeAPI.
type MockUpgradeAPIMockRecorder struct {
	mock *MockUpgradeAPI
}

// NewMockUpgradeAPI creates a new mock instance.
func NewMockUpgradeAPI(ctrl *gomock.Controller) *MockUpgradeAPI {
	mock := &MockUpgradeAPI{ctrl: ctrl}
	mock.recorder = &MockUpgradeAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgradeAPI) EXPECT() *MockUpgradeAPIMockRecorder {
	return m.recorder
}

// CordonNodeForUpgrade mocks base method.
func (m *MockUpgradeAPI) CordonNodeForUpgrade(ctx context.Context, devConfig *v1beta1.DeviceConfig, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CordonNodeForUpgrade", ctx, devConfig, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// CordonNodeForUpgrade indicates an expected call of CordonNodeForUpgrade.
func (mr *MockUpgradeAPIMockRecorder) CordonNodeForUpgrade(ctx, devConfig, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CordonNodeForUpgrade", reflect.TypeOf((*MockUpgradeAPI)(nil).CordonNodeForUpgrade), ctx, devConfig, node)
}

// GetNodeForUpgrade mocks base method.
func (m *MockUpgradeAPI) GetNodeForUpgrade(ctx context.Context, devConfig *v1beta1.DeviceConfig, nodes []v1.Node) *v1.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeForUpgrade", ctx, devConfig, nodes)
	ret0, _ := ret[0].(*v1.Node)
	return ret0
}

// GetNodeForUpgrade indicates an expected call of GetNodeForUpgrade.
func (mr *MockUpgradeAPIMockRecorder) GetNodeForUpgrade(ctx, devConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeForUpgrade", reflect.TypeOf((*MockUpgradeAPI)(nil).GetNodeForUpgrade), ctx, devConfig, nodes)
}

// GetTargetedNodes mocks base method.
func (m *MockUpgradeAPI) GetTargetedNodes(ctx context.Context, devConfig *v1beta1.DeviceConfig) ([]v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetedNodes", ctx, devConfig)
	ret0, _ := ret[0].([]v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetedNodes indicates an expected call of GetTargetedNodes.
func (mr *MockUpgradeAPIMockRecorder) GetTargetedNodes(ctx, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetedNodes", reflect.TypeOf((*MockUpgradeAPI)(nil).GetTargetedNodes), ctx, devConfig)
}

// GetUpgradedNode mocks base method.
func (m *MockUpgradeAPI) GetUpgradedNode(ctx context.Context, devConfig *v1beta1.DeviceConfig, nodes []v1.Node) *v1.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradedNode", ctx, devConfig, nodes)
	ret0, _ := ret[0].(*v1.Node)
	return ret0
}

// GetUpgradedNode indicates an expected call of GetUpgradedNode.
func (mr *MockUpgradeAPIMockRecorder) GetUpgradedNode(ctx, devConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradedNode", reflect.TypeOf((*MockUpgradeAPI)(nil).GetUpgradedNode), ctx, devConfig, nodes)
}

// KickoffUpgrade mocks base method.
func (m *MockUpgradeAPI) KickoffUpgrade(ctx context.Context, devConfig *v1beta1.DeviceConfig, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KickoffUpgrade", ctx, devConfig, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// KickoffUpgrade indicates an expected call of KickoffUpgrade.
func (mr *MockUpgradeAPIMockRecorder) KickoffUpgrade(ctx, devConfig, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KickoffUpgrade", reflect.TypeOf((*MockUpgradeAPI)(nil).KickoffUpgrade), ctx, devConfig, node)
}

// RemoveUpgradeLabels mocks base method.
func (m *MockUpgradeAPI) RemoveUpgradeLabels(ctx context.Context, devConfig *v1beta1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUpgradeLabels", ctx, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUpgradeLabels indicates an expected call of RemoveUpgradeLabels.
func (mr *MockUpgradeAPIMockRecorder) RemoveUpgradeLabels(ctx, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUpgradeLabels", reflect.TypeOf((*MockUpgradeAPI)(nil).RemoveUpgradeLabels), ctx, devConfig)
}

// UncordonUpgradedNode mocks base method.
func (m *MockUpgradeAPI) UncordonUpgradedNode(ctx context.Context, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UncordonUpgradedNode", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// UncordonUpgradedNode indicates an expected call of UncordonUpgradedNode.
func (mr *MockUpgradeAPIMockRecorder) UncordonUpgradedNode(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UncordonUpgradedNode", reflect.TypeOf((*MockUpgradeAPI)(nil).UncordonUpgradedNode), ctx, node)
}
