apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.servingNamespace }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    {{- if .Values.serviceMesh.enabled }}
    istio-injection: enabled
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- if .Values.serviceMesh.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- if .Values.serverless.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- if .Values.openshiftAI.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.openshiftAI.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.openshiftAI.namespace }}
  namespace: {{ .Values.openshiftAI.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: {{ .Values.openshiftAI.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.openshiftAI.channel }}
  installPlanApproval: Automatic
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
